apiVersion: v1
kind: Service
metadata:
  name: scenario-02-n-plus-one
  namespace: test-scenerios
spec:
  type: LoadBalancer
  selector:
    app: scenario-02
  ports:
    - port: 80
      targetPort: 3000
