---
apiVersion: v1
kind: Service
metadata:
  name: scenario-03-oomkilled
  namespace: test-scenerios
  labels:
    scenario: "03-oomkilled-memory-leak"
spec:
  selector:
    app: scenario-03
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
