apiVersion: apps/v1
kind: Deployment
metadata:
  name: scenario-11-quota
  labels:
    scenario: "11-resource-quota-exceeded"

spec:
  replicas: 1

  selector:
    matchLabels:
      app: scenario-11

  template:
    metadata:
      labels:
        app: scenario-11

    spec:
      containers:
      - name: app
        image: REGISTRY_PLACEHOLDER/scenario-11-resource-quota-exceeded:latest

        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
