---
apiVersion: v1
kind: Service
metadata:
  name: scenario-10-liveness-probe
  namespace: test-scenerios
  labels:
    scenario: "10-liveness-probe-failure"
spec:
  selector:
    app: scenario-10
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
