---
apiVersion: v1
kind: Service
metadata:
  name: scenario-16-bg-panic
  namespace: test-scenerios
  labels:
    scenario: "16-background-goroutine-panic"
spec:
  selector:
    app: scenario-16
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
