---
apiVersion: v1
kind: Service
metadata:
  name: scenario-05-pvc-pending
  namespace: test-scenerios
  labels:
    scenario: "05-pvc-pending"
spec:
  selector:
    app: scenario-05
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
